name: DataPortal - Tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.6]
        gemfile: [ rails_5, rails_6 ]
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run tests
      run: bundle exec rspec
